import Link from "next/link";
import { Heart, Sparkles } from "lucide-react";
import type { ReactNode } from "react";
import { BrandMark } from "@/components/brand/BrandMark";

export function AuthShell({ children, register = false }: { children: ReactNode; register?: boolean }) {
  return <div className="hc-canvas min-h-dvh p-4 sm:p-7"><div className="mx-auto grid min-h-[calc(100dvh-2rem)] max-w-[1350px] overflow-hidden rounded-[32px] border border-white/80 bg-white/45 shadow-[0_24px_65px_rgba(22,40,49,.1)] lg:min-h-[calc(100dvh-3.5rem)] lg:grid-cols-2">
    <div className="flex flex-col px-5 py-7 sm:px-12 lg:px-16 lg:py-10"><Link href="/" className="hc-brand w-fit"><BrandMark />HavenCare</Link><div className="my-auto w-full max-w-lg py-12"><div className="mb-5 inline-flex items-center gap-2 rounded-full bg-[#1a7f8e]/10 px-4 py-2 text-xs font-extrabold text-[#0b5963]"><Sparkles size={15}/> Ruang aman untuk setiap langkah</div><h1 className="text-3xl font-extrabold tracking-tight sm:text-4xl">{register ? "Mulai perjalananmu di sini" : "Selamat datang kembali"}</h1><p className="hc-muted mt-2 leading-relaxed">{register ? "Buat akun untuk memulai refleksi dan pendampingan yang sesuai kebutuhanmu." : "Masuk dan lanjutkan perjalanan menuju kesejahteraan diri."}</p><div className="hc-auth-content mt-7">{children}</div></div><p className="hc-muted text-xs">HavenCare AI adalah teman refleksi, bukan pengganti tenaga kesehatan.</p></div>
    <aside className="relative hidden flex-col justify-between overflow-hidden bg-gradient-to-br from-[#d9f2f5] via-[#cde9e9] to-[#b9d9d0] p-12 lg:flex"><div className="absolute -right-28 top-[-90px] h-96 w-96 rounded-full bg-[#f3c969]/30 blur-2xl"/><div className="absolute -left-24 bottom-[-150px] h-[440px] w-[440px] rounded-full bg-[#1a7f8e]/20 blur-xl"/><div className="relative z-10 inline-flex w-fit items-center gap-2 rounded-full border border-white/75 bg-white/60 px-4 py-2 text-xs font-extrabold text-[#0b5963]"><Heart size={15}/> HavenCare • Ada untukmu</div><div className="relative z-10 text-center"><div className="mx-auto flex justify-center"><BrandMark large /></div><h2 className="mt-9 text-3xl font-extrabold leading-tight">Ketenangan dimulai dari<br/>ruang yang aman</h2><p className="mx-auto mt-4 max-w-md text-[#49636a]">Satu tempat untuk memahami perasaan, menemukan dukungan, dan bertumbuh sesuai ritmemu.</p></div><div className="hc-glass relative z-10 rounded-3xl p-5 text-sm font-semibold text-[#49636a]">🌿 “Tidak perlu terburu-buru. Satu langkah kecil hari ini pun berarti.”</div></aside>
  </div></div>;
}
